//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFRs.DAL {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class DALSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static DALSetting defaultInstance = ((DALSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DALSetting())));
        
        public static DALSetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(DESCRIPTION =(ADDRESS_LIST =(ADDRESS = (PROTOCOL = TCP)(HOST = 10.9." +
            "101.26)(PORT = 1521)))(CONNECT_DATA =(SID = lsncisdb)(SERVER = DEDICATED)));User" +
            " ID=ebao_ls_prod_read;Password=password;")]
        public string EBAO_LS_ConnectionString {
            get {
                return ((string)(this["EBAO_LS_ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SL-DEVFRDB01;Initial Catalog=LS_OSC_UOB;Persist Security Info=True;Us" +
            "er ID=LS_OSC_DEV;Password=3L89gBvqqV8DymCL")]
        public string OSCConnectionString {
            get {
                return ((string)(this["OSCConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(DESCRIPTION =(ADDRESS_LIST =(ADDRESS = (PROTOCOL = TCP)(HOST = 10.9." +
            "101.26)(PORT = 1521)))(CONNECT_DATA =(SID = glsncisdb)(SERVER = DEDICATED)));Use" +
            "r ID=ebao_gls_prod_read;Password=password;")]
        public string EBAO_GLS_ConnectionString {
            get {
                return ((string)(this["EBAO_GLS_ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(DESCRIPTION =(ADDRESS_LIST =(ADDRESS = (PROTOCOL = TCP)(HOST = 10.9." +
            "105.175)(PORT = 1521)))(CONNECT_DATA =(SID = dmslife)(SERVER = DEDICATED)));User" +
            " ID=dms_al;Password=passw0rd;")]
        public string DMS_ConnectionString {
            get {
                return ((string)(this["DMS_ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.5.12.134;Initial Catalog=SmartLife;Persist Security Info=True;User" +
            " ID=usrsmartlifereadonly;Password=Selife#2023")]
        public string SMART_RP_ConnectionString {
            get {
                return ((string)(this["SMART_RP_ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SL-DEVFRDB01;Initial Catalog=CFRs;Persist Security Info=True;User ID=" +
            "sa;Password=P@ssw0rd")]
        public string CFRsConnectionString {
            get {
                return ((string)(this["CFRsConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.9.105.199;Initial Catalog=201_SELIC;Persist Security Info=True;Use" +
            "r ID=INFB1;Password=P@ssword4")]
        public string SAP_ConnectionString {
            get {
                return ((string)(this["SAP_ConnectionString"]));
            }
        }
    }
}
